server {
    listen 80;
    server_name _;

    # Frontend Angular app
    location / {
        proxy_pass http://crud-frontend:80;
    }

    # Backend API
    location /api/ {
        proxy_pass http://crud-backend:3000/;
    }
}
