  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Write SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/dd-key.pem
          chmod 600 ~/.ssh/dd-key.pem

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H 13.218.230.140 >> ~/.ssh/known_hosts

      - name: Deploy on EC2
        run: |
          ssh -i ~/.ssh/dd-key.pem ubuntu@13.218.230.140 << 'EOF'
          cd /opt/mean-app/crud-dd-task-mean-app

          # Auto-handle Nginx local file changes
          git stash --include-untracked
          git pull origin main --rebase

          # Restart containers to pull latest code & config
          docker compose down
          docker compose pull
          docker compose up -d --remove-orphans

          docker ps
          EOF
