name: CI-CD MEAN App

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/crud-dd-backend:latest ./backend

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/crud-dd-frontend:latest ./frontend

      - name: Push images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/crud-dd-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/crud-dd-frontend:latest

  deploy:
  needs: build-and-push
  runs-on: ubuntu-latest

  steps:
    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/dd-key.pem
        chmod 600 ~/.ssh/dd-key.pem

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy on EC2
      run: |
        ssh -i ~/.ssh/dd-key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        set -e

        cd /opt/mean-app/crud-dd-task-mean-app

        
        git fetch origin main
        git reset --hard origin/main

        
        docker-compose pull backend
        docker-compose up -d backend
        docker logs crud-backend


        docker ps
        EOF